spring.application.name=maptest

spring.profiles.active=naver
# Oracle 데이터베이스 연결
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=maptest
spring.datasource.password=oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernated 6.X 이후부터 Oracle12cDialect나 밑에 처럼 설정해주지 않아도 됨
#spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# H2 내장 서버 연결 방법
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console